##
## EPITECH PROJECT, 2025
## PROJECT [WSL: Ubuntu]
## File description:
## poll.ingress.yaml
##

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: __APP_NAME_INGRESS__
  namespace: default
spec:
  ingressClassName: traefik
  rules:
    - host: __HOST_NAME__
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: __APP_NAME_DNS__
                port:
                  number: __PORT__
