kind: Service
apiVersion: v1
metadata:
  name: traefik
  namespace: kube-public
spec:
  selector:
    app: traefik
  type : NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30021
      protocol : TCP
    - name: admin
      port: 8080
      targetPort: 8080
      nodePort: 30042
      protocol : TCP
